CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY
    email VARCHAR(100) NOT NULL UNIQUE
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    modified_date modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
)